name: Django CI (SQLite + Quality Checks)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install flake8 coverage

      - name: Run flake8 linting
        run: |
          cd messaging_app
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run migrations
        run: |
          cd messaging_app
          python manage.py migrate

      - name: Run tests with coverage
        run: |
          cd messaging_app
          coverage run manage.py test
          coverage xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: messaging_app/coverage.xml
